### ISSUE TITLE
Royce User story

### ISSUE THREAD

**Issue by chococar** [180161T/Empathy-map#10]

**Comment by chococar** [comment]
Make it simpler to understand such as how many pages are to be printed instead of having to go into detail such as what kind of paper and what kind of ink or what kind of direction for it to be printed

**Comment by chococar** [comment]
For an air-con, the temperature can be adjusted using a phone app where it just requires whether it wants to be on or off and at what temperature and duration, instead of having to worry about fan speed, type of function it should be on such as cooling or wind

**Comment by MysticalX** [comment]
Make a control panel that allows the user to control all aspects of smart living in their home, such as air-con, lights, and security cameras. Make the control panel accessible via a simple smartphone app tethered to the main control panel by either Wi-Fi or Bluetooth.

**Comment by MysticalX** [comment]
Design a control panel that allows the user to control all aspects of smart living in their home, such as air-con, lights, and security cameras. Make the control panel accessible via a simple smartphone app that is connected to the main control panel by either Wi-Fi or Bluetooth.

**Comment by MysticalX** [comment]
Design a control panel that allows the user to

**Comment by chococar** [comment]
User says that the GUI of air-con remotes are hard to understand and configure whenever she wants to turn it on.

**Comment by chococar** [comment]
User says that the GUI of some smart living products are hard to configure such as the automated vacuum cleaner bot that allows it to go around the house. User also mentions that the vacuum tends to get stuck after going into places where it is a tight squeeze and hard to bring it back out

**Comment by chococar** [comment]
Create a webpage that simplifies the explanation of the GUI of the machine and shows how to do a basic configuration of the GUI for Users to learn
