### ISSUE TITLE
KKM : Security locks

### ISSUE THREAD

**Issue by hieratou** [180161T/Empathy-map#2]
Security locks at home may not that reliable as one key is all it takes for someone to access the house

**Comment by hieratou** [comment]
As someone who lives at home , i would want my house to be secured by something that will inform me when anyone enters my home or attempts to unlock the lock

**Comment by MysticalX** [comment]
Implement a fingerprint lock for the front door, and also multiple security cameras all around the house, with footage that can be accessed via a smartphone app.

**Comment by hieratou** [comment]
Implement a fingerprint lock for the front door, and also multiple security cameras all around the house, with footage that can be accessed via a smartphone app. If someone tries to enter the house , it will send a notification.
