### ISSUE TITLE
Yusuf's User story

### ISSUE THREAD

**Issue by hieratou** [180161T/Empathy-map#6]
My interviewee said that the cost of smart living is rather expensive.

**Comment by hieratou** [comment]
i would want a system that reminds me how much i have spent unnecessarily each day and make me feel guilty so that i can save more money

**Comment by MysticalX** [comment]
Implement a savings tracker into the smart living system that allows users to input their daily spending, and track total amount spent monthly.

**Comment by Sofware12** [comment]
Implement a savings tracker into the smart living system that allows users to input their daily spending,their goal limit  for their monthly electricity/water bill and track total amount spent monthly.This would help in managing their expenses and help them afford smart living devices.

**Comment by Sofware12** [comment]
To solve that ,i would want a system that keeps track of my expenses and lets me know if my water/electricity bill has exceeded my monthly goal.

**Comment by Sofware12** [comment]
Implement a savings tracker into the smart living system that allows users to input their daily spending,their goal limit  for their monthly electricity/water bill and track total amount spent monthly.This would help in managing their expenses and help them afford smart living devices.
